clinic-info:
  name: 'my clinic'
  working-hours: '8-17'
  specializations:
        - dentist
        - therapist
        - surgeon
        - intern

spring:
    datasource:
#        url: jdbc:postgresql:pet_clinic # for lessons
        url: jdbc:postgresql://localhost:5433/pet_clinic # for hw
        username: postgres
        password: 123

    jackson:
#        property-naming-strategy: SNAKE_CASE
        serialization:
            write-dates-as-timestamps: false # for java.time
            indent-output: true # for java.time
    jpa:
#        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: update  #DROP and CREATE database in production 'validate'
        open-in-view: false

#logging.level.org.hibernate: DEBUG