clinic-info:
  name: 'my clinic'
  working-hours: '8-17'
  specializations:
      - Dentist
      - Therapist
      - Surgeon
      - Intern

spring:
    datasource:
        url: jdbc:postgresql:pet_clinic
        username: postgres
        password: 123

    jackson:
        property-naming-strategy: SNAKE_CASE
        serialization:
            write-dates-as-timestamps: false
            indent-output: true
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: create

#logging.level.org.hibernate: DEBUG